title: Dikson Rodrigues
description: Full Stack Developer / ReactJs, ReactNative, NodeJs
site_title: '@dr - Dikson Rodrigues'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: DiksonRodrigues
blog_url: https://github.com/DiksonRodrigues
email: eoscreativetech@gmail.com
keybase_username: 
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/perfil.png

# Google Analytics ID
google_analytics: 